// packages/comark-svelte/src/components/Markdown.svelte
<!--
@component
High-level Markdown component that accepts a markdown string, parses it, and renders it.

Uses `$state` and `$effect` for async parsing — no experimental features required.
Renders nothing until the first parse completes.

@example
```svelte
<script>
  import { Markdown } from '@comark/svelte'
  import Alert from './Alert.svelte'

  let content = `
# Hello World

::alert{type="info"}
This is an alert component
::
`
</script>

<Markdown value={content} components={{ alert: Alert }} />
```
-->
<script lang="ts">
  import type { MarkdownDocument as MarkdownDocumentType, ComarkPlugin, ComponentManifest } from 'comark'
  import { createSerializedMarkdownParser, getMarkdownParser } from 'comark'
  import type { ComarkParseFn } from 'comark'
  import { isMarkdownDocument } from 'comark/utils'
  import MarkdownDocument from './MarkdownDocument.svelte'

  let {
    value,
    options = {},
    plugins = [],
    parser,
    unwrap = false,
    components = {},
    componentsManifest,
    streaming = false,
    caret = false,
    data,
    class: className = '',
  }: {
    value?: string | MarkdownDocumentType
    options?: Record<string, any>
    plugins?: ComarkPlugin[]
    unwrap?: boolean | string | string[]
    components?: Record<string, any>
    componentsManifest?: ComponentManifest
    streaming?: boolean
    caret?: boolean | { class: string }
    data?: Record<string, unknown>
    class?: string
  } = $props()

  let parsed: MarkdownDocumentType | null = $state(null)

  let content = $derived(typeof value === 'string' ? value.trim() : '')

  // Streaming keeps incremental state inside the parser closure, and every
  // non-streaming parse resets it, so a streaming instance must own its parser.
  // Non-streaming instances share one, which is where the win is.
  function resolveParser() {
    if (parser) return parser
    const parseOptions = { ...options, ...(unwrap ? { unwrap } : {}), plugins: [...plugins] }
    return streaming ? createSerializedMarkdownParser(parseOptions) : getMarkdownParser(parseOptions)
  }

  let requestVersion = 0
  let appliedVersion = 0
  $effect(() => {
    if (isMarkdownDocument(value)) return
    const currentVersion = ++requestVersion
    // `parse` directly mutates `plugins` which creates an infinite effect loop
    // so we copy it before passing it in so it gets a regular JS array and we get to still
    // track dependencies from an external perspective
    resolveParser()(content).then((result) => {
      if (currentVersion > appliedVersion) {
        appliedVersion = currentVersion
        parsed = result
      }
    })
  })
</script>

{#if isMarkdownDocument(value)}
  <MarkdownDocument
    {value}
    {components}
    {componentsManifest}
    {streaming}
    {caret}
    {data}
    class={className}
  />
{:else if parsed}
  <MarkdownDocument
    value={parsed}
    {components}
    {componentsManifest}
    {streaming}
    {caret}
    {data}
    class={className}
  />
{/if}

// packages/comark-angular/src/components/markdown.component.ts
import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Type,
  inject,
} from '@angular/core'
import { createSerializedMarkdownParser, getMarkdownParser } from 'comark'
import type { ParserOptions, ComarkParseFn, MarkdownDocument as MarkdownDocumentType } from 'comark'
import { isMarkdownDocument } from 'comark/utils'
import { MarkdownDocument } from './markdown-document.component.ts'

/**
 * High-level Markdown component that accepts raw markdown, parses it,
 * and renders the resulting document.
 *
 * @example
 * ```html
 * <comark-markdown [value]="content" [components]="customComponents" />
 * ```
 */
@Component({
  selector: 'comark-markdown',
  standalone: true,
  imports: [MarkdownDocument],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (document) {
      <comark-markdown-document
        [value]="document"
        [components]="components"
        [streaming]="streaming"
        [caret]="caret"
        [data]="data"
      />
    }
  `,
})
export class Markdown implements OnChanges {
  /** The markdown content to parse and render, or a pre-parsed MarkdownDocument */
  @Input() value?: string | MarkdownDocumentType

  /** Parser options (excluding plugins) */
  @Input() options: Exclude<ParserOptions, 'plugins'> = {}

  /** Additional plugins to use */
  @Input() plugins: ParserOptions['plugins'] = []

  /**
   * Strip wrapper tags from the top level of the document — shorthand for
   * `options.unwrap`. `true` unwraps `<p>`; a space-separated string or array
   * unwraps the listed tags.
   */
  @Input() unwrap: boolean | string | string[] = false

  /** Custom component mappings for element tags */
  @Input() components: Record<string, Type<any>> = {}

  /** Enable streaming mode */
  @Input() streaming: boolean = false

  /** If document has a <!-- more --> comment, only render content before it */
  @Input() summary: boolean = false

  /** Append a caret to the last text node (for streaming UIs) */
  @Input() caret: boolean | { class: string } = false

  /** Additional data to pass to the renderer for :binding resolution */
  @Input() data: Record<string, unknown> = {}

  /** Parser to use instead of one resolved from `options` and `plugins` */
  @Input() parser?: ComarkParseFn

  document: MarkdownDocumentType | null = null

  private serializedParse: ComarkParseFn = getMarkdownParser({})

  private cdr = inject(ChangeDetectorRef)

  /**
   * Streaming keeps incremental state inside the parser closure, and every
   * non-streaming parse resets it, so a streaming instance must own its parser.
   * Non-streaming instances share one, which is where the win is.
   */
  private resolveParser(): ComarkParseFn {
    if (this.parser) return this.parser
    const parseOptions = {
      ...this.options,
      ...(this.unwrap ? { unwrap: this.unwrap } : {}),
      plugins: this.plugins,
    }
    return this.streaming ? createSerializedMarkdownParser(parseOptions) : getMarkdownParser(parseOptions)
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['options'] || changes['plugins'] || changes['unwrap'] || changes['streaming'] || changes['parser']) {
      this.serializedParse = this.resolveParser()
    }
    if (
      changes['value'] ||
      changes['options'] ||
      changes['plugins'] ||
      changes['unwrap'] ||
      changes['streaming'] ||
      changes['summary']
    ) {
      this.parseMarkdown()
    }
  }

  private parseMarkdown(): void {
    // Pre-parsed document — skip parsing and render directly
    if (isMarkdownDocument(this.value)) {
      this.document = this.value
      this.cdr.markForCheck()
      return
    }

    let source = (this.value as string | undefined) ?? ''
    if (this.summary) {
      source = source.split('<!-- more -->')[0] || ''
    }
    source = source.trim()

    this.serializedParse(source, { streaming: this.streaming }).then((result) => {
      this.document = result
      this.cdr.markForCheck()
    })
  }
}
